---

- name: Gather Nexus Facts
  hosts: nxos
  connection: httpapi
  gather_facts: yes

  tasks:
    - name: Change Eth 1/1 Port Description
      nxos_interface:
        name: Ethernet1/1
        description: 'uplink to core'

    - nxos_facts:
    - name: Debugging Description
      debug: var=ansible_net_interfaces['Ethernet1/1']['description']

    - name: Verify Change was Made
      assert: { that: "ansible_net_interfaces['Ethernet1/1']['description'] == 'uplink to core'"}

